### PR TITLE
[SW-733] Update licenses

### PR DESCRIPTION
**Pull request by khughes-bdai**
## Change Overview

Added some missing copyright headers, updated some license dates, and added a new license to `spot_examples`

## Testing Done

N/A

### CODE REVIEW

**Review by bhung-bdai — APPROVED** [review]
Are we going to have to do this for each year...?

**Comment by amessing-bdai** [comment]
@bhung-bdai Yep. You need to update it when you update a file if it is in a new year. Also, should we at some point change `Boston Dynamics AI Institute` to `The AI Institute`?

**Review by amessing-bdai — APPROVED** [review]

**Comment by khughes-bdai** [comment]
@amessing-bdai all of the LICENSEs in the sub-packages of spot_ros2 say `The AI Institute` but the root repo one says `Boston Dynamics AI Institute`, I can also change that one in this PR? But either way I think they should all be the same

**Comment by bhung-bdai** [comment]
Ugh. not looking forward to changing all of the files

**Comment by khughes-bdai** [comment]
### Merge activity

* **Apr 10, 4:26 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/340) failed to merge this pull request due to **internal failures**. Try your merge again, or report a bug if you see this consistently.

**Review by bhung-bdai — APPROVED** [review]

**Pull request merged**
