### PR TITLE
[SW-62] Publish hand images

### PR DESCRIPTION
**Pull request by amessing-bdai**
[SW-66] Also, exposes "has_arm" as a ros parameter that can be queried via a service client (https://roboticsbackend.com/ros2-global-parameters/)

[SW-66]: https://theaiinstitute.atlassian.net/browse/SW-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by amessing-bdai** [comment]
The corresponding spot_wrapper PR has been merged

**Review by jbarry-bdai — COMMENTED** [review]
Did you test that we're still getting data from the other cameras at the right rate?  (8hz ish I believe @davidwatkins-bdai knows for sure)

**Comment by amessing-bdai** [comment]
David Watkins and I tested this on Friday.

**Review by jbarry-bdai — COMMENTED** [review]
I'll merge once @davidwatkins-bdai approves :)

**Comment by davidwatkins-bdai** [comment]
Yes we still get the correct publishing rate, however these changes means that we are no longer publishing compressed images. This will mean that any downstream subscribers to these images will require more bandwidth. I think we should merge these changes but with a caveat to determine how to publish compressed images in the future as a ticket.

**Pull request merged**
