### PR TITLE
Updating install script to use ROS2 messages 3.3.2

### PR DESCRIPTION
**Pull request by gremigi-bdai**
In this PR I'm updating the `spot_ros2` installation script to download and install the debian packages containing the ROS2 messages for Post SDK 3.3.2.

Because the script depends on the `spot_wrapper`, the following PR must be approved first:

https://github.com/bdaiinstitute/spot_wrapper/pull/77

### CODE REVIEW

**Review by bhung-bdai — COMMENTED** [review]
I will test this on a local branch

**Comment by gremigi-bdai** [comment]
I'm getting this error when running the install script. I think we need to figure it out before approving the PR;
`E: Unable to locate package ros-humble-tf-transformations`

**Comment by bhung-bdai** [comment]
> I'm getting this error when running the install script. I think we need to figure it out before approving the PR:
> 
> ```
> E: Unable to locate package ros-humble-tf-transformations
> ```
> 
> The problem can be reproduced in BDAi docker container with the following command:
> 
> ```
> sudo apt install ros-humble-tf-transformations
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package ros-humble-tf-transformations
> ```

Are you doing this inside a clean docker? I'm not seeing this issue when I run `./install_spot_ros2.sh` inside or outside the docker. If so, running `RUN apt-get update && apt-get install ....` will likely fix it inside your Dockerfile

**Comment by bhung-bdai** [comment]
> > I'm getting this error when running the install script. I think we need to figure it out before approving the PR:
> > ```
> > E: Unable to locate package ros-humble-tf-transformations
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The problem can be reproduced in BDAi docker container with the following command:
> > ```
> > sudo apt install ros-humble-tf-transformations
> > Reading package lists... Done
> > Building dependency tree... Done
> > Reading state information... Done
> > E: Unable to locate package ros-humble-tf-transformations
> > ```
> 
> Are you doing this inside a clean docker? I'm not seeing this issue when I run `./install_spot_ros2.sh` inside or outside the docker. If so, running `RUN apt-get update && apt-get install ....` will likely fix it inside your Dockerfile

Pulling the latest docker from our repo may also fix the dependency issues.

**Comment by bhung-bdai** [comment]
> > > I'm getting this error when running the install script. I think we need to figure it out before approving the PR:
> > > ```
> > > E: Unable to locate package ros-humble-tf-transformations
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The problem can be reproduced in BDAi docker container with the following command:
> > > ```
> > > sudo apt install ros-humble-tf-transformations
> > > Reading package lists... Done
> > > Building dependency tree... Done
> > > Reading state information... Done
> > > E: Unable to locate package ros-humble-tf-transformations
> > > ```
> > 
> > 
> > Are you doing this inside a clean docker? I'm not seeing this issue when I run `./install_spot_ros2.sh` inside or outside the docker. If so, running `RUN apt-get update && apt-get install ....` will likely fix it inside your Dockerfile
> 
> Pulling the latest docker from our repo may also fix the dependency issues.

Basic examples on my end are working. If you have any updates @gremigi-bdai on your issue, let me know

**Comment by gremigi-bdai** [comment]
I added `sudo apt-get update` into the script and this solved the problem.

**Review by bhung-bdai — APPROVED** [review]
Local testing worked on my end. The included apt-get update should fix any issues with installation.

**Review by amessing-bdai — CHANGES_REQUESTED** [review]
Shouldn't there be an updated `conversions.py ` that was generated when you made the new `bosdyn_msgs`?

**Review by bhung-bdai — APPROVED** [review]
HIL testing appears all in order.

**Pull request merged**
