### PR TITLE
adjusted the encoding names of ROS image messages 

### PR DESCRIPTION
**Pull request by philipsgithub**
(if 'passthrough' is selected)

it also supports SPOT with greyscale body cameras

### CODE REVIEW

**Comment by kaiyu-zheng** [comment]
Thanks for the fix. Looks good -- will test it with our colored camera Spots.
I assume you've tested it with greyscale camera Spots?  If you run `rqt_image_view` and set the topic to a grayscale image, does the image show up?

**Comment by jbarry-bdai** [comment]
@DavidWatkins any idea on this one?

**Comment by davidwatkins-bdai** [comment]
This makes sense. I had only ever tested with RGB images and I believe a recent change enabled greyscale images to be published using `spot_ros2`.

**Comment by davidwatkins-bdai** [comment]
Yes we can merge after #72

**Comment by skpawar1305** [comment]
> (if 'passthrough' is selected)
> 
> it also supports SPOT with greyscale body cameras

afaik, passthrough isn't allowed to be passed as encoding in c++ subscriber, there we need to specifically mention again. so it's better if the message has the correct encoding mentioned in it

**Comment by skpawar1305** [comment]
> @philipsgithub Can you write a test for this and run it on a robot? In order to evaluate this change I need to determine if it can run live on a robot. 

we can close this as I've handled it here 

https://github.com/bdaiinstitute/spot_ros2/commit/ca1269a22aec58cea89b257e569923b38911ec30

**Comment by skpawar1305** [comment]
> Thanks for the fix. Looks good -- will test it with our colored camera Spots. I assume you've tested it with greyscale camera Spots? If you run `rqt_image_view` and set the topic to a grayscale image, does the image show up?

you changed it from passthrough here
https://github.com/bdaiinstitute/spot_ros2/pull/69/commits/4100d39f015033bf865b48bd4d5f2ea1482c3f60#diff-4c742ea2ddc64dd059473ffca0d127c9559bac63995c96dd509969297f61b365R157

**Comment by davidwatkins-bdai** [comment]
@skpawar1305 @philipsgithub What is the plan with this PR? Is this subsumed by #61 or should this still be merged in? If it should still be merged can one of you resolve the merge conflicts with main so I can test?

**Comment by skpawar1305** [comment]
> @skpawar1305 @philipsgithub What is the plan with this PR? Is this subsumed by #61 or should this still be merged in? If it should still be merged can one of you resolve the merge conflicts with main so I can test?

please merge both
https://github.com/bdaiinstitute/spot_ros2/pull/61 handles building correct image request
this PR handles the encoding of output image
please try it sooner as my student job contract is over :(

**Comment by jbarry-bdai** [comment]
@bhung-bdai @mpickett-bdai can one of you run this PR and make sure images are still publishing?  if you verify that we can approve and push it.

**Comment by mpickett-bdai** [comment]
@jbarry-bdai Tested on one of our spots and looks good

**Review by jbarry-bdai — APPROVED** [review]

**Comment by philipsgithub** [comment]
sorry i was on a business trip without the possibility to test anything:/... now i am back:)

**Pull request merged**
