### PR TITLE
Updating robot description files to ROS 2 and enforcing style consistency in launch files

### PR DESCRIPTION
**Pull request by daviddorf2023**

### CODE REVIEW

**Review by jbarry-bdai — COMMENTED** [review]
@gremigi-bdai @jschornak-bdai could one of you take a look at this PR since it involves launch files?

**Review by khughes-bdai — APPROVED** [review]
LGTM, tested on my computer and the functionality was the same. I think this launchfile implementation is cleaner and it also gets rid of some leftover ros1 stuff.

**Review by tcappellari-bdai — COMMENTED** [review]
This will get merged once we test it on a robot to verify functionality

**Comment by daviddorf2023** [comment]
Awesome, let me know how it goes. Hopefully it makes the file a bit clearer

**Comment by khughes-bdai** [comment]
@tcappellari-bdai Just tested this on a robot and everything still worked fine

**Review by tcappellari-bdai — APPROVED** [review]
lgtm

**Pull request merged**
