### PR TITLE
[SW-858] Remove python based image publishers

### PR DESCRIPTION
**Pull request by khughes-bdai**
## Change Overview

The python based image publishers currently don't launch and have been replaced for a while with the faster C++ image publishers. This PR deletes these Python image publishers and updates the README of spot driver with some more information of how the driver works. 

Additionally, this PR deletes an empty launchfile `view_robot.launch.py` and deletes the `.vscode` folder (which shouldn't have been there in the first place as it's in the gitignore). 

## Testing Done

- [x] CI
- [x] already addressed possible downstream effects of deleting these launchfiles in our internal repos in previous PRs.

### CODE REVIEW

**Comment by khughes-bdai** [comment]
* **#305** <a href="https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/305?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @khughes-bdai and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by bhung-bdai** [comment]
Do these not work at all? I'd ask because this is one of those things that would seem like a large enough change to cause chaos for potential users if it was working at some point and is no longer.

**Review by tcappellari-bdai — APPROVED** [review]
I agree that most likely no one is using them seeing as they don't really work anymore (and haven't for at least a few weeks). If the driver and examples and sanity checks are all still running fine and normal with these removed then I'm fine with it

**Review by bhung-bdai — APPROVED** [review]

**Comment by khughes-bdai** [comment]
### Merge activity

* **Apr 1, 11:51 AM EDT**: @khughes-bdai merged this pull request with [Graphite](https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/305).

**Pull request merged**
