### PR TITLE
[PN-60] Add node to stitch front camera images

### PR DESCRIPTION
**Pull request by jschornak-bdai**
## Change Overview

Adds `image_stitcher_node` to `spot_driver` to stitch together the front camera images and publish the stitched image and the transform to the virtual camera.

This node can get launched now when running `spot_driver.launch.py` with the launch argument `stitch_front_images:=True` (it is disabled by default). Default parameters for the image stitcher node have also been added to the example `spot_ros_example.yaml` configuration file.   Users will need to update their configuration files with these values in order to receive any meaningful stitched images as we do not launch the driver with a default configuration file. 

## Testing Done
On robot testing was successfully able to view the stitched image:

The stitched image comes in at around 1/2 the speed as the standard camera streams on my system. If this is an issue for users we can address it in a future PR. 

The default parameters for the virtual camera were verified as reasonable on 3 different robots (Opal, Lionel, and Pluto).

### CODE REVIEW

**Review by tcappellari-bdai — APPROVED** [review]
lgtm - contingent on @khughes-bdai testing being successful

**Comment by khughes-bdai** [comment]
Will plan to test this tomorrow as the wifi in the new spot lab is incredibly bad right now

**Comment by gbrooks-bdai** [comment]
Thanks @khughes-bdai and @tcappellari-bdai but I've taken over this branch from @jschornak-bdai and am still working on it.  As is this branch shouldn't really do much

**Comment by amessing-bdai** [comment]
@gbrooks-bdai I have marked this PR as do-not-merge. When you are ready you can remove the label.

**Comment by griswaldbrooks** [comment]
Will do

**Comment by tkelestemur-bdai** [comment]
Is there any update on this PR?

**Review by tcappellari-bdai — APPROVED** [review]
lgtm

**Pull request merged**
