### PR TITLE
[MAPLE-681] Add robot_description_package as parameter to driver launch

### PR DESCRIPTION
**Pull request by llee-bdai**
## Change Overview
This allows you to change the pack from where to get the robot description. This allows us to have different configurations of the robot (such as custom payloads)
Makes the (hard) assumption that whatever package you point it to has `{package}/urdf/spot.urdf.xacro` in it.

@tcappellari-bdai @khughes-bdai feel free to agree/disagree with this, but only way I could get extra collision objects in as needed on hardware

### CODE REVIEW

**Comment by khughes-bdai** [comment]
@amessing-bdai this is the alternative I thought of that uses xacro args in the main spot URDF. it should allow you to not duplicate the rest of the spot urdf internally but I don't know if this is actually a better solution 

```
...
<xacro:arg name="extras_package" default=""/>
...
<load main spot model>

<xacro:if value="$(arg extras_package)">
  <xacro:include filename="$(find extras_package)/urdf/spot_extras.urdf" />
```
then in the launchfile we could have 
```
robot_description = Command(
        [
            PathJoinSubstitution([FindExecutable(name="xacro")]),
            " ",
            PathJoinSubstitution([pkg_share, "urdf", "spot.urdf.xacro"]),
            " ",
            "arm:=",
            TextSubstitution(text=str(has_arm).lower()),
            " ",
            "tf_prefix:=",
            tf_prefix,
            " ",
            "extras_package:=",
           LaunchConfiguration(robot_description_package)
        ]
    )
```

there is also this leftover remnant from the ros1 repo https://github.com/bdaiinstitute/spot_ros2/blob/main/spot_description/urdf/empty.urdf but setting an environment variable to add extra things to your URDF seems like not a great way to do things

**Review by khughes-bdai — APPROVED** [review]
I'm good with this change, by default this doesn't change any behavior. I think this will also be a useful addition for driver integration with the custom gripper Spot. (and with the future push to separate out spot description and consolidate all of our urdfs in RDS, we might come up with a more streamlined way to add to the base spot urdf)

**Comment by amessing-bdai** [comment]
It seems better to have addons vs duplicate urdf files to me, but I wouldn't be a user. @llee-bdai thoughts?

Consolidating in RDS has some hurdles to make happen, so I wouldn't base a decision on it.

**Comment by khughes-bdai** [comment]
i think the downside of add-ons is that it's harder to expose custom arguments through the core spot URDF, so it feels less flexible

(with the custom gripper work as an example, I would want to set the xacro args `gripperless` and `custom_gripper_base_link` in order to get an add-on to the main spot URDF to work, which is not exposed through the launchfile's xacro command)

**Review by scastro-bdai — APPROVED** [review]
While I normally would agree that xacro args is better, I'm not entirely sure these "antlers" warrant being an officially supported argument until it becomes more of a standard thing. So I'm onboard with "different URDF" for the short term.

**Review by khughes-bdai — APPROVED** [review]

**Comment by llee-bdai** [comment]
### Merge activity

* **Dec 2, 4:14 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/531).

**Pull request merged**
