### PR TITLE
Add basic Dockerized CI

### PR DESCRIPTION
**Pull request by jiuguangw**

### CODE REVIEW

**Comment by MizzouRobotics** [comment]
As a quick aside. Did you have the dockerfile that was used to perform the ci tests? It might have the dependencies for what I'm missing in regards to solving my issue(https://github.com/bdaiinstitute/spot_ros2/issues/11#issue-1526797829). Thanks!

**Comment by jiuguangw** [comment]
> 

Sorry, just saw this message. If you just want to try it, you can do `docker pull ghcr.io/bdaiinstitute/spot_ros2_jammy_humble:spot_ros2_docker` and then build on top of this image. The actual Dockerfile is located in one of the other BDAII repos and is very cumbersome to share (Dockerfile + dozens of support scripts). I left a comment for your other question - if you remove gtest, you might be able to compile without going through Docker.

**Review by jbarry-bdai — APPROVED** [review]
I don't really know what the code does but I like dockerized CI!

**Review by jbarry-bdai — APPROVED** [review]

**Comment by jiuguangw** [comment]
Closed as a duplicate of PR #40

**Pull request closed without merging**
