### PR TITLE
Skip sit for shutdown Spot on driver node destruction

### PR DESCRIPTION
**Pull request by mhidalgo-bdai**
## Change Overview

Precisely what the title says. If Spot is powered off before the driver is torn down, the driver will fail to sit.

## Testing Done

Manually started the driver, powered off motors, stopped the driver.

### CODE REVIEW

**Review by bhung-bdai — APPROVED** [review]

**Comment by khughes-bdai** [comment]
Is this PR trying to accomplish the same thing? https://github.com/bdaiinstitute/spot_ros2/pull/294

**Review by amessing-bdai — APPROVED** [review]

**Comment by mhidalgo-bdai** [comment]
> Is this PR trying to accomplish the same thing? https://github.com/bdaiinstitute/spot_ros2/pull/294

Good question. This one is about not trying to sit if the robot is already powered off and sitting in the ground. That PR is attempting to remove sitting on destruction entirely. If we are going away with sitting, we don't need this.

**Comment by mhidalgo-bdai** [comment]
CC @tcappellari-bdai. Let me know what you want to do with this.

**Comment by tcappellari-bdai** [comment]
Right, I had moved my PR to the back burner because I was trying to get the shutdown process to be cleaner without that delay thing it does before all the shutdown spew sometimes when you kill the driver

**Pull request merged**
