### PR TITLE
setting up documentation prototype (sphinx + ReadTheDocs)

### PR DESCRIPTION
**Pull request by slecleach**
This is part of [https://www.notion.so/theaiinstitute/Starter-Project-Simon-Le-Cleac-h-documentation-infrastructure-70e35f3429974d5581c1057f615c4a0e](https://www.notion.so/theaiinstitute/Starter-Project-Simon-Le-Cleac-h-documentation-infrastructure-70e35f3429974d5581c1057f615c4a0e)

The final objective is to build the documentation for this repository using [Sphinx](https://www.sphinx-doc.org/en/master/). 
I am adding `__init__.py` files to subfolders to allow Sphinx to explore these folders and automatically build the documentation from docstrings.

In a later pull request, I'll add the infrastructure for building the documentation.

### CODE REVIEW

**Comment by kaiyu-zheng** [comment]
I think it's good to get people's attention and have discussions going. But I think because we squash and merge, we don't have to have a PR that prepares for the upcoming Sphinx documentation stuff? It might be better to make this PR a draft for now till the real changes are in?  Also, adding @ggoretkin-bdai to check my understanding of work flow.

**Comment by slecleach** [comment]
Thanks @kaiyu-zheng and @jiuguangw for your comments, this is very helpful. 
@jiuguangw You were right, it seems that the __init_py files are not necessary for sphinx-apidoc to document the whole package. Using the ```--implicit-namespace``` option we can document namespace packages too. 
```sphinx-apidoc --implicit-namespace -f -o source/ ../ ```.

The ```include_patterns``` flag filters which pages are going to be included in the final documentation after the pages are created by ```sphinx-apidoc```.

Since the ```__init__.py``` are not necessary, should I close this PR and open a new one with the documentation infrastructure or just update this one?

**Comment by kaiyu-zheng** [comment]
I think either way works!

**Comment by jiuguangw** [comment]
> Since the `__init__.py` are not necessary, should I close this PR and open a new one with the documentation infrastructure or just update this one?

I say just update this one...

**Review by jbarry-bdai — APPROVED** [review]

**Comment by jbarry-bdai** [comment]
Gah I didn't read the comments before just saying "looks harmless" and merging.  Sorry!  Should I revert?

**Comment by jiuguangw** [comment]
Not worth reverting. No worries.

**Pull request merged**
