### PR TITLE
[SW-681] Add PR template to spot_ros2

### PR DESCRIPTION
**Pull request by khughes-bdai**
## Change Overview

This adds a basic PR template to `spot_ros2` (which was used to fill out this PR!). It is based off the template on our internal repositories. 

## Testing Done

N/A

### CODE REVIEW

**Comment by khughes-bdai** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #261** <a href="https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/261?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/bdaiinstitute/spot_ros2/261?utm_source=stack-comment).

**Comment by khughes-bdai** [comment]
Wondering if this should also include a reviewer checklist -- in our internal repositories this is also a section of the template as there are specific requirements that we want reviewers to look for.

**Comment by amessing-bdai** [comment]
I would at least add the part about the domain coordinator

**Review by jbarry-bdai — APPROVED** [review]
Thanks!

**Review by tcappellari-bdai — APPROVED** [review]
lgtm

**Pull request merged**
