### PR TITLE
change image requests to greyscale on getting pixel format unsupporte…

### PR DESCRIPTION
**Pull request by skpawar1305**
…d error

handles https://github.com/bdaiinstitute/spot_ros2/issues/189 automatically

### CODE REVIEW

**Comment by skpawar1305** [comment]
should handle https://github.com/bdaiinstitute/spot_ros2/issues/189 automatically

**Comment by jschornak-bdai** [comment]
Is there a way to query Spot to determine what pixel formats it supports, similar to how we can ask if Spot has an arm? I think I would prefer that approach if possible.

**Comment by skpawar1305** [comment]
https://github.com/bdaiinstitute/spot_wrapper/issues/68#issue-1854668390

**Comment by skpawar1305** [comment]
> Is there a way to query Spot to determine what pixel formats it supports, similar to how we can ask if Spot has an arm? I think I would prefer that approach if possible.

I'm not sure tbh, maybe @heuristicus can answer

**Comment by heuristicus** [comment]
I don't recall seeing anything which specifically gives information about what cameras the robot has.

**Comment by joshuaoreilly** [comment]
I checkout out the [greyscale_cam](https://github.com/bdaiinstitute/spot_ros2/tree/greyscale_cam) branch before updating the submodules/continuing with installation and I still get the pixel format error described in #189, using `spot_ros_example.yaml` with `rgb_cameras: False` or not

**Comment by skpawar1305** [comment]
> I checkout out the [greyscale_cam](https://github.com/bdaiinstitute/spot_ros2/tree/greyscale_cam) branch before updating the submodules/continuing with installation and I still get the pixel format error described in #189, using `spot_ros_example.yaml` with `rgb_cameras: False` or not.

hello, i've tested it yesterday, I'll test it again today and reply👍

**Comment by skpawar1305** [comment]
> I checkout out the [greyscale_cam](https://github.com/bdaiinstitute/spot_ros2/tree/greyscale_cam) branch before updating the submodules/continuing with installation and I still get the pixel format error described in #189, using `spot_ros_example.yaml` with `rgb_cameras: False` or not.

I confirm that this PR works, please make sure you're testing with the correct branch and the packages are built correctly and let us know. Thank you

**Comment by joshuaoreilly** [comment]
> > I checkout out the [greyscale_cam](https://github.com/bdaiinstitute/spot_ros2/tree/greyscale_cam) branch before updating the submodules/continuing with installation and I still get the pixel format error described in #189, using `spot_ros_example.yaml` with `rgb_cameras: False` or not.
> 
> I confirm that this PR works, please make sure you're testing with the correct branch and the packages are built correctly and let us know. Thank you

I'll try it again on Monday and get back to you. Are you running this within a docker container, or on an Ubuntu 22.04 host? I'm attempting the former.

**Comment by bhung-bdai** [comment]
We generally run in docker containers, as it manages the dependency issues
better.

**Comment by skpawar1305** [comment]
https://github.com/bdaiinstitute/spot_ros2/discussions/131

**Comment by joshuaoreilly** [comment]
I'm still getting this issue, I've attached a Dockerfile (appended with .txt to upload) to run my setup all at once, which is essentially the [dev container](https://github.com/bdaiinstitute/spot_ros2/blob/main/.devcontainer/Dockerfile) from this repo, plus the instructions from the [README](https://github.com/bdaiinstitute/spot_ros2/tree/main#readme), and finally a simple bash script to start the driver. I'm using the latest version of this branch (built and ran a few minutes ago)

- [Dockerfile.txt](https://github.com/bdaiinstitute/spot_ros2/files/13412088/Dockerfile.txt) - Ran with `docker run --rm -it <image ID>
- [full-log.txt](https://github.com/bdaiinstitute/spot_ros2/files/13412109/full-log.txt)

**Comment by skpawar1305** [comment]
> I'm still getting this issue, I've attached a Dockerfile (appended with .txt to upload) to run my setup all at once, which is essentially the [dev container](https://github.com/bdaiinstitute/spot_ros2/blob/main/.devcontainer/Dockerfile) from this repo, plus the instructions from the [README](https://github.com/bdaiinstitute/spot_ros2/tree/main#readme), and finally a simple bash script to start the driver. I'm using the latest version of this branch (built and ran a few minutes ago)
> 
> * [Dockerfile.txt](https://github.com/bdaiinstitute/spot_ros2/files/13412088/Dockerfile.txt) - Ran with `docker run --rm -it <image ID>`
> * [full-log.txt](https://github.com/bdaiinstitute/spot_ros2/files/13412109/full-log.txt)
> 
> Again, this fails with or without specifying `rgb_cameras: False` in a yaml file

hello, thank you
I'll test with the docker file tomorrow

**Comment by joshuaoreilly** [comment]
I set [has_rgb_cameras](https://github.com/bdaiinstitute/spot_ros2/blob/c3250142399e189fe061a6d417f7bc4d389b5871/spot_driver_cpp/src/spot_image_publisher.cpp#L118) to `false` and still get:

```
[spot_image_publisher_node-2] [ERROR] [1700555251.767271540] [image_publisher]: Failed to get images: Failed to get images: 6(STATUS_UNSUPPORTED_PIXEL_FORMAT_REQUESTED): ImageResponse ::bosdyn::common::Status unsuccessful
```

I forgot to mention: we have the arm installed; Spot is greyscale for us, but the arm is RGB. I set [has_hand_camera](https://github.com/bdaiinstitute/spot_ros2/blob/c3250142399e189fe061a6d417f7bc4d389b5871/spot_driver_cpp/src/spot_image_sources.cpp#L100C33-L100C33) to `false` to temporarily ignore the arm, and sure enough, it runs now without the above error.
I think the issue may be that the first call to `createImageRequest` will fail in our case, since we have greyscale cameras on Spot, and so it'll fallback and call `createImageRequest` again with `has_rgb_cameras` set to `false`, which will also fail due to the arm camera being RBG instead of greyscale.
A "solution" I've found for this is to separately handle the case of an arm in `createImageRequest`, replacing [this](https://github.com/bdaiinstitute/spot_ros2/blob/c3250142399e189fe061a6d417f7bc4d389b5871/spot_driver_cpp/src/spot_image_publisher.cpp#L40C4-L40C4) line:

```
image_request->set_pixel_format(has_rgb_cameras ? bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_RGB_U8
                                                      : bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_GREYSCALE_U8);
```


with:

```
if (source.camera == SpotCamera::HAND) {
	image_request->set_pixel_format(bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_RGB_U8);
}
else {
	image_request->set_pixel_format(has_rgb_cameras ? bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_RGB_U8
                                                        : bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_GREYSCALE_U8);
}
```

A little hacky, but it allows it to run without the error above.

**Comment by joshuaoreilly** [comment]
I added just the following change to the main branch:

```
if (source.camera == SpotCamera::HAND) {
	image_request->set_pixel_format(bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_RGB_U8);
}
else {
	image_request->set_pixel_format(has_rgb_cameras ? bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_RGB_U8
                                                        : bosdyn::api::Image_PixelFormat_PIXEL_FORMAT_GREYSCALE_U8);
}
```

And it now works using `rgb_cameras: False` in a config file. Does this also work for you? Perhaps this PR could be reduced to the above change if so.

**Comment by skpawar1305** [comment]
@jschornak-bdai hello, would you prefer a parameter or a fallback?

also, I would like to publish greyscale images with mono8 encoding [for e.g.](https://github.com/RRL-ALeRT/spot_ros2/blob/8eebd6ea6b4ee148fc12285bf33d76e3809fc1b9/spot_cpp_ros2/src/get_image.cpp#L219)
can SpotImageType::MONO be added for the same?

**Comment by bhung-bdai** [comment]
@jschornak-bdai are we still interested in including this? It seems reasonable

**Comment by skpawar1305** [comment]
https://github.com/bdaiinstitute/spot_ros2/pull/303

**Pull request closed without merging**
