### PR TITLE
[EK-32] Add robot command service to Spot ROS 2

### PR DESCRIPTION
**Pull request by mhidalgo-bdai**
## Change Overview

This patch adds a `RobotCommand` service, alongside the `RobotCommand` action, as a fire-and-forget interface in the Spot ROS 2 node.

## Testing Done

~To be tested manually using teleop functionality.~ Tested through https://github.com/bdaiinstitute/bdai/pull/3211.

### CODE REVIEW

**Review by amessing-bdai — APPROVED** [review]

**Review by bhung-bdai — COMMENTED** [review]
Is this meant to be separately tested from teleop?

**Review by khughes-bdai — APPROVED** [review]
LGTM

**Comment by mhidalgo-bdai** [comment]
Rebased to resolve conflicts.

**Review by khughes-bdai — APPROVED** [review]

**Review by bhung-bdai — APPROVED** [review]

**Review by tcappellari-bdai — APPROVED** [review]
lgtm

**Pull request merged**
