### PR TITLE
Spot Docking and Undocking Services

### PR DESCRIPTION
**Pull request by zmk5**
This pull request will add services for both docking and undocking. The former gets its own ROS Service message to allow a user to specify a dock ID, while undocking is a `Trigger`. I originally wrote this to have the dock services always run but instead opted to use a config file to supply a `has_dock` parameter which will start the services when needed. A user can modify the `has_dock` parameter in the example `yaml` to enable use of the dock.

I've tested this with a mock behavior tree code I've written on a physical spot robot and have run and passed all the pre-commit checks. This pull request should address issue #33.

### CODE REVIEW

**Comment by heuristicus** [comment]
My preference for these kinds of things is for them to be available, unless the system physically does not have the capability. For example, if the robot is a non-enterprise model, perhaps disabling the service would make sense, but otherwise I'd have it available - the user can decide whether or not to use it, and the standard error messages from the system should suffice if it is called for some reason.

**Comment by zmk5** [comment]
That makes sense. I was under the assumption that the dock was an extra and doesn't come with Spot, so I made it an option.

If the maintainers want, I can make the service always available with a new commit.

**Review by jbarry-bdai — COMMENTED** [review]
I agree with @heuristicus that I think this should always be available rather than having people set it in the config file.  If you want to make that change and verify you tested docking, I'll approve and merge!

One other thought: things like "Dock" that last for a long time are really somewhat better as actions rather than services so that they can be interrupted.  That said, it's a lot more work to add an action than a service and this adds useful functionality so I don't object to putting it in as is.

Thanks for making a contribution!

**Comment by zmk5** [comment]
> I agree with @heuristicus that I think this should always be available rather than having people set it in the config file. If you want to make that change and verify you tested docking, I'll approve and merge!
> 
> One other thought: things like "Dock" that last for a long time are really somewhat better as actions rather than services so that they can be interrupted. That said, it's a lot more work to add an action than a service and this adds useful functionality so I don't object to putting it in as is.

Understood! I removed the `had_dock` parameter and verified it works with Spot 3.3.0.

> 
> Thanks for making a contribution!

No problem! We were adding this functionality and thought to support the team while we work on our stuff.

**Review by jbarry-bdai — APPROVED** [review]

**Pull request merged**
